참가 취소 기능 #121
ryush00/capstone pull request #123
Opened 2024-11-22 08:36 UTC by rlaxotjs123456

## 작업 내용
- 카풀 정보 참여하기 참여 취소 기능 추가

## 스크린샷
- 
![image](https://github.com/user-attachments/assets/d0b3fb38-8ae6-4ea8-8f05-e694479d7955)

## 리뷰 시 참고사항
- fix #121

2024-11-22 08:41 UTC, ryush00 requested changes

2024-11-22 08:41 UTC, ryush00 commented on app/controllers/pools_controller.rb
> +    else
카풀 기간 (end_at)이 지났을 때 참가 취소가 가능하지 않을까요? 기간이 지나면 참가 취소가 불가능하도록 추가해야 할 것 같아요,

2024-11-22 08:41 UTC, ryush00 commented on app/views/pools/show.html.erb
> +        <%= link_to '참가취소', unjoin_pool_path(@pool), class: "btn btn-danger btn-sm" %>
위쪽에 74번째 줄 참가 버튼쪽에 참가 취소 버튼을 옮기는 게 좋지 않을까요?

2024-11-22 10:43 UTC, rlaxotjs123456 commented
- [ ] 참가 버튼
- [ ] 참가취소 버튼
- [ ] 마감 버튼

2024-11-22 14:57 UTC, ryush00 commented
리뷰하면 될까요?

2024-11-23 00:47 UTC, rlaxotjs123456 commented
넵

2024-11-23 11:22 UTC, merged