회원가입 페이지 수정
ryush00/capstone pull request #15
Opened 2024-10-11 03:55 UTC by rlaxotjs123456

회원가입 페이지 수정

2024-10-11 06:10 UTC, ryush00 requested changes

2024-10-11 06:10 UTC, ryush00 commented on app/views/devise/registrations/new.html.erb
> +                        <input type="password" class="form-control" id="password"  name="user[email]"  placeholder="비밀번호를 입력하세요">
비밀번호랑 비밀번호 확인 name이 잘못 적혀있음.

2024-10-11 06:10 UTC, ryush00 commented on app/views/devise/registrations/new.html.erb
> +                        <input type="password" class="form-control" id="confirmPassword"  name="user[email]"  placeholder="비밀번호를 다시 입력하세요">
수정 필요

2024-10-27 04:55 UTC, rlaxotjs123456 commented on app/views/devise/registrations/new.html.erb
> +                        <input type="password" class="form-control" id="password"  name="user[email]"  placeholder="비밀번호를 입력하세요">
<div class="mb-3">
    <label for="password" class="form-label"><strong>비밀번호</strong></label>
    <input type="password" class="form-control" id="password" name="user[password]" placeholder="비밀번호를 입력하세요">
</div>
<div class="mb-3">
    <label for="confirmPassword" class="form-label"><strong>비밀번호 확인</strong></label>
    <input type="password" class="form-control" id="confirmPassword" name="user[confirmPassword]" placeholder="비밀번호를 다시 입력하세요">
</div>

2024-10-27 04:56 UTC, rlaxotjs123456 commented on app/views/devise/registrations/new.html.erb
> +                        <input type="password" class="form-control" id="password"  name="user[email]"  placeholder="비밀번호를 입력하세요">
<div class="mb-3">
    <label for="password" class="form-label"><strong>비밀번호</strong></label>
    <input type="password" class="form-control" id="password" name="user[password]" placeholder="비밀번호를 입력하세요">
</div>
<div class="mb-3">
    <label for="confirmPassword" class="form-label"><strong>비밀번호 확인</strong></label>
    <input type="password" class="form-control" id="confirmPassword" name="user[confirmPassword]" placeholder="비밀번호를 다시 입력하세요">
</div>

2024-10-28 00:34 UTC, ryush00 commented
#21 PR에서 처리

2024-10-28 00:34 UTC, closed without merging