카풀만들기헬퍼수정+홈삭제+단순화
ryush00/capstone pull request #56
Opened 2024-11-14 18:42 UTC by Yang0Jin0Woo

## 작업 내용
- 메인 창에서 상단 메뉴에 있는 '홈' 제거
- 카풀 만들기 html에서 레일즈 헬퍼 사용+'카풀 정보' 문구 삭제
- 카풀 찾기 클릭 후 나오는 '카풀 찾기' 문구 삭제

## 스크린샷
- 
![image](https://github.com/user-attachments/assets/adcfed41-fa48-4f9b-878e-91a70ee82e62)
- 
![image](https://github.com/user-attachments/assets/78649718-dc2e-41fe-8cd7-4da4a0076046)
-
![image](https://github.com/user-attachments/assets/c911e5de-422d-4f35-b86d-17bca613b50d)

## 리뷰 시 참고사항
-

2024-11-14 23:25 UTC, Yang0Jin0Woo commented
부트스트랩 링크 형태로 적용하려다 출발지와 도착지가 주택이거나 건물 일 수 있는 관계로 텍스트 박스 적용했습니다.
https://getbootstrap.com/docs/4.1/components/forms/#form-controls

2024-11-15 01:00 UTC, ryush00 requested changes

2024-11-15 01:01 UTC, ryush00 commented
> 부트스트랩 링크 형태로 적용하려다 출발지와 도착지가 주택이거나 건물 일 수 있는 관계로 텍스트 박스 적용했습니다. https://getbootstrap.com/docs/4.1/components/forms/#form-controls

저희의 출발지와 목적지는 학교, 역 등 이미 지정된 소수의 장소이니까, 버튼으로 여러개 중에 선택하도록 하는게 더 낫지 않을까요?

2024-11-15 02:17 UTC, ryush00 approved these changes

2024-11-15 02:17 UTC, merged